# Generated by Django 4.2.7 on 2024-01-30 20:03

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagelocus', '0032_externalauth_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSystems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=3)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('csrf_token', models.CharField(max_length=32)),
                ('sessionid', models.CharField(max_length=32)),
                ('system', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='ExternalAuth',
        ),
    ]
